version: '3.4'

services:
  bankingsystemmodeling:
    image: bankingsystemmodeling
    build:
      context: .
      dockerfile: BankingSystemModeling/Dockerfile
    ports: 
      - "4499:80"

